# Generated by Django 5.1.2 on 2024-10-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_conditions',
            field=models.CharField(blank=True, choices=[('Dry', 'Dry'), ('Mud', 'Mud'), ('Wet', 'Wet'), ('Snow', 'Snow')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='riding_style',
            field=models.CharField(blank=True, choices=[('Cross Country', 'Cross Country'), ('All Mountain', 'All Mountain'), ('Downhill', 'Downhill'), ('Freeride', 'Freeride')], max_length=20, null=True),
        ),
    ]
