# Generated by Django 5.1.2 on 2024-10-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='background_image',
            field=models.ImageField(null=True, upload_to='trail_backgrounds/'),
        ),
    ]
