# Generated by Django 4.2 on 2024-10-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_trail_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailFeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='trail_features/')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_images', to='trails.trail')),
            ],
        ),
    ]
