# Generated by Django 4.2 on 2024-10-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_trailfeatureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailfeatureimage',
            name='image_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
