# Generated by Django 4.2 on 2024-10-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='current_period_end',
            field=models.DateTimeField(null=True),
        ),
    ]
