# Generated by Django 4.2 on 2024-10-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_stripecustomer_current_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='current_period_end',
            field=models.DateTimeField(null=True),
        ),
    ]
